-- Run this in the Supabase SQL editor once.
-- https://xrfrftilofzbbvlxtcsr.supabase.co -> SQL Editor -> New query -> Run

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    full_name text not null,
    phone text not null,
    semester text not null,
    faculty text not null,
    book text not null,
    created_at timestamptz not null default now()
);

alter table public.students enable row level security;

create policy "allow all" on public.students
    for all
    using (true)
    with check (true);
